name: Windows (MSYS2 UCRT64)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true

      - name: Setup MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2.30.0
        with:
          msystem: UCRT64
          update: true
          cache: true
          install: >
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja

      - name: Configure CMake
        run: |
          cmake --preset windows-gcc-release

      - name: Build
        run: |
          cmake --build --preset windows-gcc-release

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: pyrite64-windows
          include-hidden-files: true
          path: |
            pyrite64.exe
            data
            n64
            LICENSE

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc g++ \
            libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxss-dev libxtst-dev
#            libwayland-dev libwayland-client-dev libwayland-cursor-dev libwayland-egl-dev

      - name: Configure CMake
        run: |
          cmake --preset linux-release

      - name: Build
        run: |
          cmake --build --preset linux-release

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: pyrite64-linux
          include-hidden-files: true
          path: |
            pyrite64
            data
            n64
            LICENSE

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: pyrite64-windows
          path: windows-artifact
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: pyrite64-linux
          path: linux-artifact
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Extract latest changelog entry
        id: changelog
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/}")
          awk '/^# v[0-9]+\.[0-9]+\.[0-9]+/{if (p) exit; p=1; print; next} p' Changelog.md > RELEASE_NOTES.md
          
          echo "" >> RELEASE_NOTES.md
          echo "Checkout the main repositories Readme for more information." >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "> [!WARNING]" >> RELEASE_NOTES.md
          echo "> This project is still in early development, features are going to be missing." >> RELEASE_NOTES.md
          echo "> Documentation is also still work in progress, and breaking API changes are to be expected." >> RELEASE_NOTES.md
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          draft: true
          prerelease: false
      - name: Upload Windows artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: windows-artifact/**
          tag_name: ${{ github.ref_name }}
      - name: Upload Linux artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: linux-artifact/**
          tag_name: ${{ github.ref_name }}
