name: Windows (MSYS2 UCRT64)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true

      - name: Setup MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2.30.0
        with:
          msystem: UCRT64
          update: true
          cache: true
          install: >
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja

      - name: Configure CMake
        run: |
          cmake --preset windows-gcc-release

      - name: Build
        run: |
          cmake --build --preset windows-gcc-release

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: pyrite64-windows
          include-hidden-files: true
          path: |
            pyrite64.exe
            data
            n64
            LICENSE

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc g++ \
            libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxss-dev libxtst-dev
#            libwayland-dev libwayland-client-dev libwayland-cursor-dev libwayland-egl-dev

      - name: Configure CMake
        run: |
          cmake --preset linux-release

      - name: Build
        run: |
          cmake --build --preset linux-release

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: pyrite64-linux
          include-hidden-files: true
          path: |
            pyrite64
            data
            n64
            LICENSE
